- id: doi:10.1038/nm.3599
  image: images/logo.svg
 
- id: doi:10.1016/j.immuni.2016.12.011
  image: images/logo.svg

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
#   extra-links:
#     - type: preprint
#       link: https://doi.org/10.7287/peerj.preprints.3100v1
#     - type: manubot
#       link: https://greenelab.github.io/scihub-manuscript/
#     - type: source
#       link: https://github.com/greenelab/scihub-manuscript
#       text: Manuscript source
#     - type: source
#       link: https://github.com/greenelab/scihub
#       text: Analyses source
#   tags:
#     - knowledge graphs
